/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package networkprogramming.p2pfiletransfer;

public class App {

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
}
