/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package networkprogramming.p2pfiletransfer;

import java.io.File;
import java.io.IOException;

import networkprogramming.p2pfiletransfer.Utils.GZipHelper;
import networkprogramming.p2pfiletransfer.Utils.ObjectSocket;
import networkprogramming.p2pfiletransfer.Utils.Packet;
import javax.swing.JFileChooser;
import org.apache.commons.io.FileUtils;
import java.nio.file.Path;


/**
 *
 * @author vanlinh
 */
public class FileRequestNoti extends javax.swing.JFrame {
        private final ObjectSocket objSocket;
        private final Packet packet;

        public FileRequestNoti(ObjectSocket objSocket, Packet packet) {
                initComponents();
                this.objSocket = objSocket;
                this.packet = packet;
                name.setText(packet.getMachineName());
                IP.setText(packet.getFromIP());
                port.setText(String.valueOf(packet.getFromPort()));
                fileName.setText(packet.getFileName());
                message.setText(packet.getMessage());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                IPLabel = new javax.swing.JLabel();
                nameLabel = new javax.swing.JLabel();
                messageLabel = new javax.swing.JLabel();
                title = new javax.swing.JLabel();
                fileLabel = new javax.swing.JLabel();
                fileName = new javax.swing.JTextField();
                name = new javax.swing.JTextField();
                IP = new javax.swing.JTextField();
                port = new javax.swing.JTextField();
                portLabel = new javax.swing.JLabel();
                acceptButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                message = new javax.swing.JTextArea();
                denyButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                IPLabel.setText("IP");

                nameLabel.setText("Name");

                messageLabel.setText("Message");

                title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                title.setText("FILE TRANSFER REQUEST");
                title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                fileLabel.setText("File");

                fileName.setEditable(false);
                fileName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                fileName.setFocusable(false);

                name.setEditable(false);
                name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                name.setFocusable(false);

                IP.setEditable(false);
                IP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                IP.setToolTipText("");
                IP.setFocusable(false);

                port.setEditable(false);
                port.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                port.setFocusable(false);

                portLabel.setText("Port");

                acceptButton.setText("Accept");
                acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                acceptButtonMouseClicked(evt);
                        }
                });

                message.setEditable(false);
                message.setColumns(20);
                message.setRows(5);
                message.setFocusable(false);
                jScrollPane1.setViewportView(message);

                denyButton.setText("Deny");
                denyButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                denyButtonMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(title,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(messageLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                49,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(fileLabel,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(IPLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(nameLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jScrollPane1)
                                                                                                                                .addComponent(name)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(IP,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                147,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(portLabel)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(port))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(acceptButton,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                171,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                .addComponent(denyButton,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                176,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addComponent(fileName))))
                                                                .addGap(20, 20, 20)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(title,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(name,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                28, Short.MAX_VALUE)
                                                                                .addComponent(nameLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                                .addComponent(port,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                28,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(portLabel,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(IP,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                .addComponent(IPLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(fileLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(fileName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jScrollPane1)
                                                                                .addComponent(messageLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(acceptButton)
                                                                                .addComponent(denyButton))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_acceptButtonMouseClicked
                try {
                        JFileChooser fileChooser = new JFileChooser();
                        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                        int returnVal = fileChooser.showSaveDialog(null);
                    
                        if (returnVal == JFileChooser.APPROVE_OPTION) {
                          File selectedPath = fileChooser.getSelectedFile();

                          byte[] data = packet.getData();
                          data = GZipHelper.decompress(data);
                          Path filePath = Path.of(selectedPath.toString(), packet.getFileName());
                          
                          FileUtils.writeByteArrayToFile(new File(filePath.toString()), data);
                          objSocket.getWriter().writeObject(new Packet(1));
                        } 
                        else {
                          System.out.println("Save operation cancelled.");                        
                          objSocket.getWriter().writeObject(new Packet(2));
                        }
                        setVisible(false);
                        dispose();
                } catch (IOException ex) {
                        ex.printStackTrace();
                }

        }// GEN-LAST:event_acceptButtonMouseClicked

        private void denyButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_denyButtonMouseClicked
                try {
                        objSocket.getWriter().writeObject(new Packet(2));
                        setVisible(false);
                        dispose();
                } catch (IOException ex) {
                        ex.printStackTrace();
                }
        }// GEN-LAST:event_denyButtonMouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField IP;
        private javax.swing.JLabel IPLabel;
        private javax.swing.JButton acceptButton;
        private javax.swing.JButton denyButton;
        private javax.swing.JLabel fileLabel;
        private javax.swing.JTextField fileName;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea message;
        private javax.swing.JLabel messageLabel;
        private javax.swing.JTextField name;
        private javax.swing.JLabel nameLabel;
        private javax.swing.JTextField port;
        private javax.swing.JLabel portLabel;
        private javax.swing.JLabel title;
        // End of variables declaration//GEN-END:variables
}
