/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package networkprogramming.p2pfiletransfer;

import java.awt.Color;
import java.net.*;
import java.io.*;
import javax.swing.JFileChooser;
import org.apache.commons.io.FileUtils;
import networkprogramming.p2pfiletransfer.Utils.*;

/**
 *
 * @author vanlinh
 */
public class MainUI extends javax.swing.JFrame {

        /**
         * Creates new form MainUI
         */
        private P2PServerThread serverThread;
        private P2PClientThread clientThread;
        private byte[] fileContent;
        private String fileName;

        public MainUI() {
                initComponents();
                Socket socket = new Socket();
                try {
                        socket.connect(new InetSocketAddress("google.com", 80));
                        IP.setText(socket.getLocalAddress().getHostAddress());
                        socket.close();

                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();
                IPLabel = new javax.swing.JLabel();
                portLabel = new javax.swing.JLabel();
                clientPortLabel = new javax.swing.JLabel();
                clientIPLabel = new javax.swing.JLabel();
                fileLabel = new javax.swing.JLabel();
                fileButton = new javax.swing.JButton();
                listenButton = new javax.swing.JButton();
                sendFileButton = new javax.swing.JButton();
                nameLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                message = new javax.swing.JTextArea();
                messageLabel = new javax.swing.JLabel();
                title = new javax.swing.JLabel();
                name = new javax.swing.JTextField();
                IP = new javax.swing.JTextField();
                port = new javax.swing.JTextField();
                clientIP = new javax.swing.JTextField();
                clientPort = new javax.swing.JTextField();
                filePath = new javax.swing.JTextField();
                checkButton = new javax.swing.JButton();

                jTextArea2.setColumns(20);
                jTextArea2.setRows(5);
                jScrollPane2.setViewportView(jTextArea2);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                IPLabel.setText("IP");

                portLabel.setText("Port");

                clientPortLabel.setText("Client port");

                clientIPLabel.setText("Client IP");

                fileLabel.setText("File");

                fileButton.setText("...");
                fileButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                fileButtonMouseClicked(evt);
                        }
                });

                listenButton.setText("Listen");
                listenButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                listenButtonMouseClicked(evt);
                        }
                });

                sendFileButton.setText("Send file");
                sendFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                sendFileButtonMouseClicked(evt);
                        }
                });

                nameLabel.setText("Name");

                message.setColumns(20);
                message.setRows(5);
                jScrollPane1.setViewportView(message);

                messageLabel.setText("Message");

                title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                title.setText("P2P FILE TRANSFER");
                title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                name.setHorizontalAlignment(javax.swing.JTextField.LEFT);

                IP.setEditable(false);
                IP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                IP.setToolTipText("");
                IP.setFocusable(false);

                port.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                clientIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                clientIP.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                clientIPMouseClicked(evt);
                        }
                });

                clientPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                clientPort.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                clientPortMouseClicked(evt);
                        }
                });

                filePath.setEditable(false);
                filePath.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                filePath.setFocusable(false);

                checkButton.setText("Check");
                checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                checkButtonMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(title,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                                .addComponent(nameLabel,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(clientIPLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(fileLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(messageLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(IPLabel,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jScrollPane1)
                                                                                                                                .addComponent(name)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(filePath,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                333,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(fileButton,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                42,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(IP,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                153,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(clientIP))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(portLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(clientPortLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(clientPort)
                                                                                                                                                                .addComponent(port,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                70,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(listenButton,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(checkButton,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE))))))
                                                                .addGap(20, 20, 20))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(150, 150, 150)
                                                                .addComponent(sendFileButton,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(150, 150, 150)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(title,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(name,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                28, Short.MAX_VALUE)
                                                                                .addComponent(nameLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                                .addComponent(port)
                                                                                                                .addComponent(portLabel,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(IP,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(listenButton,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                28,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(5, 5, 5)
                                                                                                                                .addComponent(clientPortLabel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                23,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(clientPort,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                27,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(checkButton,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                27,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(clientIP,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                28,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(IPLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(clientIPLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(fileLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(filePath,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(fileButton,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jScrollPane1)
                                                                                .addComponent(messageLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(sendFileButton)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void sendFileButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_sendFileButtonMouseClicked
                var machineName = name.getText();
                var fromIP = IP.getText();
                var toIP = clientIP.getText();
                var fromPort = Integer.parseInt(port.getText());
                var toPort = Integer.parseInt(clientPort.getText());
                var hostMessage = message.getText();
                var fileInfo = new Packet(0, fileContent, machineName, fromIP, toIP, fromPort, toPort, fileName, hostMessage);
                clientThread = new P2PClientThread(clientIP.getText(), Integer.parseInt(port.getText()), fileInfo);
                clientThread.start();
        }// GEN-LAST:event_sendFileButtonMouseClicked

        private void fileButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_fileButtonMouseClicked
                if (fileButton.getText().equals("...")) {
                        JFileChooser fileChooser = new JFileChooser();
                        int chooser = fileChooser.showOpenDialog(null);

                        if (chooser == JFileChooser.APPROVE_OPTION) {
                                File selectedFile = fileChooser.getSelectedFile();
                                filePath.setText(selectedFile.getPath());
                                try {
                                        fileContent = FileUtils.readFileToByteArray(selectedFile);
                                        fileContent = GZipHelper.compress(fileContent);
                                        fileName = selectedFile.getName();
                                } catch (Exception e) {
                                        e.printStackTrace();
                                }
                        }
                        fileButton.setText("x");
                } else if (fileButton.getText().equals("x")) {
                        filePath.setText("");
                        fileContent = null;
                        fileButton.setText("...");
                }
        }// GEN-LAST:event_fileButtonMouseClicked

        private void clientIPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clientIPMouseClicked
                clientIP.setForeground(Color.BLACK);
        }// GEN-LAST:event_clientIPMouseClicked

        private void clientPortMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clientPortMouseClicked
                clientPort.setForeground(Color.BLACK);
        }// GEN-LAST:event_clientPortMouseClicked

        private boolean isListening(String host, int port) throws IOException {
                Socket s = null;
                try {
                        s = new Socket(host, port);
                } catch (Exception e) {
                        s.close();
                        return false;
                }
                s.close();
                return true;
        }

        private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_checkButtonMouseClicked
                checkButton.setEnabled(false);
                try {
                        if (isListening(clientIP.getText(), Integer.parseInt(clientPort.getText()))) {
                                clientIP.setForeground(Color.GREEN);
                                clientPort.setForeground(Color.GREEN);
                        } else {
                                clientIP.setForeground(Color.RED);
                                clientPort.setForeground(Color.RED);
                        }
                } catch (Exception e) {}
                
                checkButton.setEnabled(true);
        }// GEN-LAST:event_checkButtonMouseClicked

        private void listenButtonMouseClicked(java.awt.event.MouseEvent evt) { // GEN-FIRST:event_listenButtonMouseClicked
                if (listenButton.getText().equals("Listen")) {
                        listenButton.setText("Stop");
                        try {
                                serverThread = new P2PServerThread(Integer.parseInt(port.getText()));
                                serverThread.start();
                        } catch (Exception e) {
                                e.printStackTrace();
                                serverThread = null;
                        }
                } else if (listenButton.getText().equals("Stop")) {
                        listenButton.setText("Listen");
                        if (serverThread != null)
                                serverThread.interrupt();
                                serverThread = null;
                }
        }// GEN-LAST:event_listenButtonMouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField IP;
        private javax.swing.JLabel IPLabel;
        private javax.swing.JButton checkButton;
        private javax.swing.JTextField clientIP;
        private javax.swing.JLabel clientIPLabel;
        private javax.swing.JTextField clientPort;
        private javax.swing.JLabel clientPortLabel;
        private javax.swing.JButton fileButton;
        private javax.swing.JLabel fileLabel;
        private javax.swing.JTextField filePath;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea2;
        private javax.swing.JButton listenButton;
        private javax.swing.JTextArea message;
        private javax.swing.JLabel messageLabel;
        private javax.swing.JTextField name;
        private javax.swing.JLabel nameLabel;
        private javax.swing.JTextField port;
        private javax.swing.JLabel portLabel;
        private javax.swing.JButton sendFileButton;
        private javax.swing.JLabel title;
        // End of variables declaration//GEN-END:variables
}
